version: '3'
services:
  reverse-proxy: 
    image: traefik:v2.4
    ports:
      - 80:80
      - 8080:8080 #Management UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
  whoami:
    image: traefik/whoami:v1.10
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
