api:
  dashboard: true
  insecure: true
#Enable Docker Provider
providers:
  docker:
    watch: true
    exposedByDefault: false
#    swarmMode: false
#Logging
log:
  level: INFO # In production WARNING or ERROR

#Entrypoints
entryPoints:
  web:
    address: ":80"
